import test from 'node:test';
import assert from 'node:assert/strict';
import {parseYouTubeUrl, selectCaptionLanguage, formatCaptions, fetchYouTubeLecture} from './youtube.js';

test('requires an actual HTTPS YouTube video link', () => {
  assert.equal(parseYouTubeUrl('https://youtu.be/abcdefghijk').videoId, 'abcdefghijk');
  assert.equal(parseYouTubeUrl('https://www.youtube.com/watch?v=abcdefghijk&t=22').sourceUrl, 'https://www.youtube.com/watch?v=abcdefghijk');
  assert.throws(() => parseYouTubeUrl('https://youtube.com.evil.test/watch?v=abcdefghijk'));
  assert.throws(() => parseYouTubeUrl('https://www.youtube.com/playlist?list=123'));
});

test('prefers the spoken auto-generated language and preserves timestamps', () => {
  const selected = selectCaptionLanguage([{languageCode:'en',isAutoGenerated:false},{languageCode:'hi',isAutoGenerated:true}]);
  assert.equal(selected.languageCode, 'hi');
  assert.equal(formatCaptions([{offset:72.4,text:'  First\n idea  '},{offset:3723,text:' Next idea '}]), '[01:12] First idea\n[1:02:03] Next idea');
});

test('fetches title and original captions, warning without interrupting', async () => {
  const calls = [];
  const result = await fetchYouTubeLecture('https://youtu.be/abcdefghijk', {
    listLanguagesImpl: async id => { calls.push(id); return [{languageCode:'hi',isAutoGenerated:true}]; },
    fetchTranscriptImpl: async (id, options) => {
      calls.push(options.lang);
      return {videoDetails:{title:'  Algorithms lecture  '},segments:[{offset:0,lang:'hi',text:'A topic explained clearly. '.repeat(20)}]};
    }
  });
  assert.deepEqual(calls, ['abcdefghijk', 'hi']);
  assert.equal(result.title, 'Algorithms lecture');
  assert.equal(result.languageWarning, true);
  assert.match(result.captions, /^\[00:00\]/);
});

test('explains when the server cannot reach YouTube instead of leaking fetch failed', async () => {
  const networkError = new TypeError('fetch failed', {cause:Object.assign(new Error('blocked'), {code:'EACCES'})});
  await assert.rejects(
    fetchYouTubeLecture('https://youtu.be/abcdefghijk', {listLanguagesImpl:async () => { throw networkError; }}),
    /could not reach YouTube/i
  );
});
